name: Firebase

on:
  push:
    branches:
    - master
jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    needs: chrome
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 10.x
    - uses: DamianReeves/write-file-action@v1.0
      with:
        path: .env.production
        contents: |
          MATOMO_URL=${{ secrets.MATOMO_URL }}
          MATOMO_SITE_ID=${{ secrets.MATOMO_SITE_ID }}
        write-mode: overwrite
    - run: npm install
    - run: MVC_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} MVC_FIREBASE_DOMAIN=${{ secrets.FIREBASE_DOMAIN }} npm run build
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:minimum-viable-ceremonies --project ${{ secrets.FIREBASE_DOMAIN }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
